server:
  port: ${USER_SERVICE_PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public