server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: 9957

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false
